version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./files:/usr/src/app/files
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  worker:
    build: .
    command: ["python", "-m", "worker.worker"]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_cookie
      - RABBITMQ_DEFAULT_USER=user  # Replace 'user' with your desired username
      - RABBITMQ_DEFAULT_PASS=password  # Replace 'passw

volumes:
  rabbitmq_data:
